#!/bin/bash

readonly CONTROLLER="${MODEL}Controller"
readonly FACADE="${MODEL}Facade"
readonly SERVICE="${MODEL}Service"
readonly REPOSITORY="${MODEL}Repository"
readonly ENTITY="${MODEL}Entity"
readonly DTO="${MODEL}Dto"
readonly MAPPER="${MODEL}Mapper";
readonly ADD_PARAM="Add${MODEL}Param"
readonly UPDATE_PARAM="Update${MODEL}Param"

get_controller_parsed () {
    local CONTROLLER_TEMPLATE=''
    local API_BASE_PATH=''

    API_BASE_PATH=$(echo "${MODEL,}" | sed -r 's/([a-z0-9])([A-Z])/\1-\L\2/g')

    CONTROLLER_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/controller-template)
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{API_BASE_PATH\}/${API_BASE_PATH}}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{DTO_CLASS_NAME\}/$DTO}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{DTO_VAR_NAME\}/${DTO,}}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{CONTROLLER_CLASS_NAME\}/$CONTROLLER}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{FACADE_CLASS_NAME\}/$FACADE}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{FACADE_VAR_NAME\}/${FACADE,}}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{MODEL_NAME\}/$MODEL}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{MODEL_NAME_LOWER\}/${MODEL,}}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{UPDATE_MODEL_PARAM_CLASS_NAME\}/$UPDATE_PARAM}
    CONTROLLER_TEMPLATE=${CONTROLLER_TEMPLATE//\{ADD_MODEL_PARAM_CLASS_NAME\}/$ADD_PARAM}

    echo "${CONTROLLER_TEMPLATE}"
}


get_dto_parsed () {
    local DTO_TEMPLATE=''

    DTO_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/dto-template)
    DTO_TEMPLATE=${DTO_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    DTO_TEMPLATE=${DTO_TEMPLATE//\{DTO_CLASS_NAME\}/$DTO}
    echo "${DTO_TEMPLATE}"
}


get_facade_parsed () {
    local FACADE_TEMPLATE=''

    FACADE_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/facade-template)
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{FACADE_CLASS_NAME\}/${FACADE}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{MAPPER_CLASS_NAME\}/${MAPPER}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{SERVICE_CLASS_NAME\}/${SERVICE}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{SERVICE_VAR_NAME\}/${SERVICE,}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{DTO_CLASS_NAME\}/${DTO}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{MODEL_NAME\}/${MODEL}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{MODEL_NAME_LOWER\}/${MODEL,}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{ADD_MODEL_PARAM_CLASS_NAME\}/${ADD_PARAM}}
    FACADE_TEMPLATE=${FACADE_TEMPLATE//\{UPDATE_MODEL_PARAM_CLASS_NAME\}/${UPDATE_PARAM}}

    echo "${FACADE_TEMPLATE}"

}


get_add_param_parsed () {
    local ADD_PARAM_TEMPLATE=''

    ADD_PARAM_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/add-param-template)
    ADD_PARAM_TEMPLATE=${ADD_PARAM_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    ADD_PARAM_TEMPLATE=${ADD_PARAM_TEMPLATE//\{ADD_PARAM_CLASS_NAME\}/${ADD_PARAM}}

    echo "${ADD_PARAM_TEMPLATE}"
}

get_update_param_parsed () {
    local UPDATE_PARAM_TEMPLATE=''

    UPDATE_PARAM_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/update-param-template)
    UPDATE_PARAM_TEMPLATE=${UPDATE_PARAM_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    UPDATE_PARAM_TEMPLATE=${UPDATE_PARAM_TEMPLATE//\{UPDATE_PARAM_CLASS_NAME\}/${UPDATE_PARAM}}

    echo "${UPDATE_PARAM_TEMPLATE}"
}

get_service_parsed () {
    local SERVICE_TEMPLATE=''

    SERVICE_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/service-template)
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{REPOSITORY_CLASS_NAME\}/${REPOSITORY}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{REPOSITORY_VAR_NAME\}/${REPOSITORY,}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{SERVICE_CLASS_NAME\}/${SERVICE}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{ENTITY_CLASS_NAME\}/${ENTITY}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{MODEL_NAME\}/${MODEL}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{MODEL_NAME_LOWER\}/${MODEL,}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{ADD_MODEL_PARAM_CLASS_NAME\}/${ADD_PARAM}}
    SERVICE_TEMPLATE=${SERVICE_TEMPLATE//\{UPDATE_MODEL_PARAM_CLASS_NAME\}/${UPDATE_PARAM}}

    echo "${SERVICE_TEMPLATE}"
}

get_entity_parsed () {
    local ENTITY_TEMPLATE=''
    local ENTITY_TABLE_NAME=''

    ENTITY_TABLE_NAME=$(echo "${MODEL,}"| sed -r 's/([a-z0-9])([A-Z])/\1_\L\2/g')

    ENTITY_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/entity-template)
    ENTITY_TEMPLATE=${ENTITY_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    ENTITY_TEMPLATE=${ENTITY_TEMPLATE//\{ENTITY_CLASS_NAME\}/${ENTITY}}
    ENTITY_TEMPLATE=${ENTITY_TEMPLATE//\{ENTITY_TABLE_NAME\}/${ENTITY_TABLE_NAME,}}

    echo "${ENTITY_TEMPLATE}"
}

get_repository_parsed () {
    local REPOSITORY_TEMPLATE=''

    REPOSITORY_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/repository-template)
    REPOSITORY_TEMPLATE=${REPOSITORY_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    REPOSITORY_TEMPLATE=${REPOSITORY_TEMPLATE//\{MODEL_NAME\}/${MODEL}}
    REPOSITORY_TEMPLATE=${REPOSITORY_TEMPLATE//\{ENTITY_CLASS_NAME\}/${ENTITY}}

    echo "${REPOSITORY_TEMPLATE}"
}

get_mapper_parsed () {
    local MAPPER_TEMPLATE=''

    MAPPER_TEMPLATE=$(/usr/bin/cat "${SCRIPT_PATH}"/templates/mapper-template)
    MAPPER_TEMPLATE=${MAPPER_TEMPLATE//\{PACKAGE\}/${PACKAGE}}
    MAPPER_TEMPLATE=${MAPPER_TEMPLATE//\{MODEL_NAME\}/${MODEL}}
    MAPPER_TEMPLATE=${MAPPER_TEMPLATE//\{DTO_CLASS_NAME\}/${DTO}}
    MAPPER_TEMPLATE=${MAPPER_TEMPLATE//\{ENTITY_CLASS_NAME\}/${ENTITY}}
    MAPPER_TEMPLATE=${MAPPER_TEMPLATE//\{ENTITY_VAR_NAME\}/${MODEL,}}

    echo "${MAPPER_TEMPLATE}"
}

export -f get_controller_parsed
export -f get_facade_parsed
export -f get_service_parsed
export -f get_repository_parsed
export -f get_add_param_parsed
export -f get_update_param_parsed
export -f get_dto_parsed
export -f get_entity_parsed
export -f get_mapper_parsed